from genericpath import exists
import os
import ctypes


def getTargetDirectory():
    '''Fetch target directory to save audio files generated by GTTS'''
    hideFile = ctypes.windll.kernel32.SetFileAttributesW  # hide file in windows system
    targetFolderName = ".BatteryMonitor"
    if os.name == "posix":
        for user, userName in os.environ.items():
            if user == "USER":
                targetDirectory = f"/home/{userName}/{targetFolderName}"
                if not os.path.exists(targetDirectory):
                    os.mkdir(targetDirectory)
                    os.chdir(targetDirectory)
    else:
        for user, userName in os.environ.items():
            if user == "USERNAME":
                targetDirectory = f"C:/Users/{userName}/{targetFolderName}"
                if not os.path.exists(targetDirectory):
                    os.mkdir(targetDirectory)
                os.chdir(targetDirectory)
                hideFile(targetDirectory, 2)
