import os


def createTargetDirectory():
    """Fetch .BatteryMonitor folder inside User folder to save audio files generated by GTTS"""
    for user, userName in os.environ.items():
        if user == "USERNAME":
            if os.name == "posix":
                targetDirectory = f"/home/{userName}/.BatteryMonitor"
            else:
                targetDirectory = f"C:/Users/{userName}/.BatteryMonitor"

            if not os.path.exists(targetDirectory):
                os.mkdir(targetDirectory)
            os.chdir(targetDirectory)

            try:
                import ctypes

                hideFileFlag = 0x02
                ctypes.windll.kernel32.SetFileAttributesW(
                    targetDirectory, hideFileFlag)

            except:
                pass
